"use server";
import { revalidatePath } from "next/cache";
import { requireRole } from "@/lib/permissions/authorization";
import { createAdminClient } from "@/lib/supabase/admin";
import type { AdminActionResult } from "@/lib/admin-action";
import { z } from "zod";
import type { Json } from "@/types/database";

export async function confirmImportAction(data:FormData):Promise<AdminActionResult>{const principal=await requireRole("admin");const id=z.uuid().safeParse(String(data.get("jobId")??""));if(!id.success)return{error:"Invalid import job."};const{data:count,error}=await createAdminClient().rpc("confirm_import_job_as_admin",{target_job_id:id.data,actor_profile_id:principal.id});if(error)return{error:error.message};revalidatePath("/admin/imports");return{success:`Import completed atomically: ${count??0} records created.`};}

const mappingSchema=z.object({jobId:z.uuid(),field:z.enum(["type_code","transaction_type_code","loan_type_code","rebate_type_code","leave_type_code","category_code"]),from:z.string().trim().min(1),to:z.string().trim().min(1)});
export async function applyImportMappingAction(data:FormData):Promise<AdminActionResult>{const principal=await requireRole("admin");const parsed=mappingSchema.safeParse({jobId:data.get("jobId"),field:data.get("field"),from:data.get("from"),to:data.get("to")});if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Invalid mapping."};const admin=createAdminClient();const table={type_code:"transaction_types",transaction_type_code:"transaction_types",loan_type_code:"loan_types",rebate_type_code:"rebate_types",leave_type_code:"leave_types",category_code:"document_categories"}[parsed.data.field] as "transaction_types";const{data:target}=await admin.from(table).select("code").ilike("code",parsed.data.to).eq("is_active",true).is("deleted_at",null).maybeSingle();if(!target)return{error:"The replacement code is not an active configuration."};const{data:rows}=await admin.from("import_rows").select("id,normalized_data,error_message").eq("import_job_id",parsed.data.jobId).eq("status","error").eq("error_code","UNKNOWN_REFERENCE");let updated=0;for(const row of rows??[]){const normalized=row.normalized_data as Record<string,unknown>|null;if(!normalized||String(normalized[parsed.data.field]??"").toLowerCase()!==parsed.data.from.toLowerCase())continue;normalized[parsed.data.field]=target.code;const remaining=String(row.error_message??"").split(/(?<=\.)\s+/).filter(message=>!message.toLowerCase().includes(`unknown ${parsed.data.field}: ${parsed.data.from.toLowerCase()}`));await admin.from("import_rows").update({normalized_data:normalized as Json,status:remaining.length?"error":"valid",error_code:remaining.length?"VALIDATION_ERROR":null,error_message:remaining.join(" ")||null,updated_by:principal.id}).eq("id",row.id);updated++;}const{count:errorCount}=await admin.from("import_rows").select("id",{count:"exact",head:true}).eq("import_job_id",parsed.data.jobId).eq("status","error");const{count:validCount}=await admin.from("import_rows").select("id",{count:"exact",head:true}).eq("import_job_id",parsed.data.jobId).eq("status","valid");await admin.from("import_jobs").update({error_rows:errorCount??0,valid_rows:validCount??0,status:(errorCount??0)===0?"ready":"validating",updated_by:principal.id,summary:{last_mapping:{field:parsed.data.field,from:parsed.data.from,to:parsed.data.to}}}).eq("id",parsed.data.jobId);revalidatePath("/admin/imports");return{success:`Mapped ${updated} row(s). Review the preview before confirmation.`};}
