export type RoundingMethod="half_up"|"down"|"up"; export type CalculationStrategy="manual"|"zero_interest"|"flat_percentage";
export type ScheduleRow={installment_number:number;due_date:string;principal_due:string;interest_due:string;penalty_due:string;other_due:string;total_due:string;rule_snapshot:Record<string,unknown>};
const SCALE=6n,FACTOR=10n**SCALE,CENTS=10n**4n;
function parse(value:string){const sign=value.startsWith("-")?-1n:1n;const clean=value.replace("-","");const[whole="0",fraction=""]=clean.split(".");return sign*(BigInt(whole||"0")*FACTOR+BigInt(fraction.padEnd(Number(SCALE),"0").slice(0,Number(SCALE))||"0"));}
function rounded(value:bigint,method:RoundingMethod){const base=value/CENTS;const rest=value%CENTS;if(rest===0n)return base; if(method==="down")return base;if(method==="up")return base+(value>=0?1n:-1n);return base+(rest*2n>=CENTS?1n:0n);}
function formatCents(cents:bigint){const abs=cents<0n?-cents:cents;return`${cents<0n?"-":""}${abs/100n}.${String(abs%100n).padStart(2,"0")}`;}
function addDueDate(start:string,index:number,frequency:string){const date=new Date(`${start}T00:00:00Z`);if(frequency==="weekly")date.setUTCDate(date.getUTCDate()+7*index);else if(frequency==="semi_monthly")date.setUTCDate(date.getUTCDate()+15*index);else if(frequency==="quarterly")date.setUTCMonth(date.getUTCMonth()+3*index);else date.setUTCMonth(date.getUTCMonth()+index);return date.toISOString().slice(0,10);}
export function calculateLoanPreview(input:{principal:string;rate:string;term:number;startDate:string;frequency:string;strategy:CalculationStrategy;rounding:RoundingMethod}){if(input.term<1)throw new Error("Term must be positive.");const principal=parse(input.principal);if(principal<=0n)throw new Error("Principal must be positive.");const rate=parse(input.rate);const interest=input.strategy==="flat_percentage"?principal*rate/(100n*FACTOR):0n;const total=principal+interest;const totalCents=rounded(total,input.rounding);const principalCents=rounded(principal,input.rounding);const interestCents=totalCents-principalCents;let allocatedPrincipal=0n,allocatedInterest=0n;const rows:ScheduleRow[]=[];for(let i=1;i<=input.term;i++){const last=i===input.term;const installment=last?totalCents-allocatedPrincipal-allocatedInterest:totalCents/BigInt(input.term);const p=last?principalCents-allocatedPrincipal:principalCents/BigInt(input.term);const interestPart=last?interestCents-allocatedInterest:installment-p;allocatedPrincipal+=p;allocatedInterest+=interestPart;rows.push({installment_number:i,due_date:addDueDate(input.startDate,i,input.frequency),principal_due:formatCents(p),interest_due:formatCents(interestPart),penalty_due:"0.00",other_due:"0.00",total_due:formatCents(p+interestPart),rule_snapshot:{strategy:input.strategy,rate:input.rate,rounding:input.rounding,configuration_version:1}});}return{principal:formatCents(principalCents),interest:formatCents(interestCents),total:formatCents(totalCents),rows};}
export function calculateRebatePreview(input:{baseAmount:string;strategy:string;fixedAmount?:string;percentage?:string;rounding:string}){if(input.strategy==="manual")return null;if(!["fixed_amount","percentage"].includes(input.strategy))return null;const method=(["half_up","down","up"].includes(input.rounding)?input.rounding:"half_up") as RoundingMethod;const raw=input.strategy==="fixed_amount"?parse(input.fixedAmount??"0"):parse(input.baseAmount)*parse(input.percentage??"0")/(100n*FACTOR);return formatCents(rounded(raw,method));}
