"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Calculator } from "lucide-react";
import { toast } from "sonner";

import { adjustLoanScheduleAction, createLoanAction, recordLoanPaymentAction, replaceLoanScheduleAction } from "./actions";
import type { CreditType, LoanEmployee, LoanTypeOption, Schedule } from "./loan-manager";
import { AdminFormActions } from "@/components/admin/admin-form-layout";
import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { calculateLoanPreview, type CalculationStrategy, type RoundingMethod } from "@/lib/finance/calculations";

function runAction(action: (data: FormData) => Promise<{ error?: string; success?: string }>, data: FormData, done: () => void, start: React.TransitionStartFunction) { start(async () => { const result = await action(data); if (result.error) return toast.error(result.error); toast.success(result.success); done(); }); }

export function NewLoanForm({ employees, loanTypes }: { employees: LoanEmployee[]; loanTypes: LoanTypeOption[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [principal, setPrincipal] = useState("10000.00"); const [rate, setRate] = useState("0"); const [term, setTerm] = useState(12); const [start, setStart] = useState(new Date().toISOString().slice(0, 10)); const [frequency, setFrequency] = useState("monthly"); const [strategy, setStrategy] = useState<CalculationStrategy>("manual"); const [rounding, setRounding] = useState<RoundingMethod>("half_up"); const [source, setSource] = useState<"manual" | "system">("manual"); const [scheduleJson, setScheduleJson] = useState("");
  const preview = useMemo(() => { try { return calculateLoanPreview({ principal, rate, term, startDate: start, frequency, strategy, rounding }); } catch { return null; } }, [principal, rate, term, start, frequency, strategy, rounding]);
  return <form onSubmit={(event) => { event.preventDefault(); runAction(createLoanAction, new FormData(event.currentTarget), () => { router.push("/admin/loans"); router.refresh(); }, startTransition); }}><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><SelectField label="Employee" name="employeeId" options={employees.map((employee) => [employee.id, `${employee.employee_number} · ${employee.last_name}`])} /><SelectField label="Loan type" name="loanTypeId" options={loanTypes.map((type) => [type.id, `${type.code} · ${type.name}`])} /><Field label="Loan reference" name="loanNumber" required /><div className="space-y-2"><Label>Principal</Label><Input name="principal" value={principal} onChange={(event) => setPrincipal(event.target.value)} inputMode="decimal" /></div><div className="space-y-2"><Label>Interest rate (%)</Label><Input name="rate" value={rate} onChange={(event) => setRate(event.target.value)} inputMode="decimal" /></div><div className="space-y-2"><Label>Term</Label><Input name="term" type="number" min="1" value={term} onChange={(event) => setTerm(Number(event.target.value))} /></div><div className="space-y-2"><Label>Start date</Label><Input name="startDate" type="date" value={start} onChange={(event) => setStart(event.target.value)} /></div><Field label="Maturity date" name="maturityDate" type="date" /><ControlledSelect label="Frequency" name="frequency" value={frequency} setValue={setFrequency} options={["weekly", "semi_monthly", "monthly", "quarterly"]} /><ControlledSelect label="Interest method" name="strategy" value={strategy} setValue={(value) => setStrategy(value as CalculationStrategy)} options={["manual", "zero_interest", "flat_percentage"]} /><ControlledSelect label="Rounding" name="rounding" value={rounding} setValue={(value) => setRounding(value as RoundingMethod)} options={["half_up", "down", "up"]} /><ControlledSelect label="Value source" name="source" value={source} setValue={(value) => setSource(value as "manual" | "system")} options={["manual", "system"]} /><div className="border bg-muted/20 p-4 sm:col-span-2 lg:col-span-3"><p className="flex items-center gap-2 font-semibold"><Calculator className="size-4" />Preview</p><p className="mt-2 text-sm">Principal ₱{preview?.principal ?? "—"} + interest ₱{preview?.interest ?? "—"} = <b>₱{preview?.total ?? "—"}</b></p><Button type="button" variant="outline" className="mt-3" onClick={() => setScheduleJson(JSON.stringify(preview?.rows ?? [], null, 2))}>Use preview schedule</Button></div><div className="space-y-2 sm:col-span-2 lg:col-span-3"><Label>Schedule rows</Label><Textarea name="scheduleJson" rows={10} value={scheduleJson} onChange={(event) => setScheduleJson(event.target.value)} className="font-mono text-xs" /></div></div><AdminFormActions cancelHref="/admin/loans" pending={pending} submitLabel="Create loan" /></form>;
}

export function LoanPaymentForm({ loanId, creditTypes }: { loanId: string; creditTypes: CreditType[] }) { const router = useRouter(); const [pending, startTransition] = useTransition(); return <form onSubmit={(event) => { event.preventDefault(); runAction(recordLoanPaymentAction, new FormData(event.currentTarget), () => { router.push("/admin/loans"); router.refresh(); }, startTransition); }}><input type="hidden" name="loanId" value={loanId} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Payment date" name="date" type="date" required value={new Date().toISOString().slice(0, 10)} /><Field label="Amount" name="amount" required /><SelectField label="Credit transaction type" name="transactionTypeId" options={creditTypes.map((type) => [type.id, type.name])} /><Field label="Reference" name="reference" /><div className="space-y-2 sm:col-span-2"><Label>Notes</Label><Textarea name="notes" /></div></div><AdminFormActions cancelHref="/admin/loans" pending={pending} submitLabel="Post payment" /></form>; }

export function ScheduleReplacementForm({ loanId, schedules }: { loanId: string; schedules: Schedule[] }) { const router = useRouter(); const [pending, startTransition] = useTransition(); const [confirm, setConfirm] = useState(false); const [method, setMethod] = useState("manual"); const [reason, setReason] = useState(""); const [scheduleJson, setScheduleJson] = useState(JSON.stringify(schedules.map(({ id, loan_id, paid_amount, status, ...row }) => ({ ...row, rule_snapshot: { source: "manual replacement" } })), null, 2)); const submit = () => { const data = new FormData(); data.set("loanId", loanId); data.set("method", method); data.set("reason", reason); data.set("scheduleJson", scheduleJson); runAction(replaceLoanScheduleAction, data, () => { router.push("/admin/loans"); router.refresh(); }, startTransition); }; return <><div className="space-y-5"><ControlledSelect label="Method" name="method" value={method} setValue={setMethod} options={["manual", "automatic"]} /><div className="space-y-2"><Label>Schedule rows</Label><Textarea rows={14} className="font-mono text-xs" value={scheduleJson} onChange={(event) => setScheduleJson(event.target.value)} /></div><div className="space-y-2"><Label>Reason</Label><Textarea value={reason} onChange={(event) => setReason(event.target.value)} required minLength={5} /></div><div className="sticky bottom-0 flex justify-end gap-2 border-t bg-background/95 py-4"><Button type="button" variant="outline" onClick={() => router.push("/admin/loans")}>Cancel</Button><Button type="button" onClick={() => setConfirm(true)}>Review replacement</Button></div></div><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Replace payment schedule?</AlertDialogTitle><AlertDialogDescription>Existing unpaid rows are soft-deleted. Schedules with allocations cannot be replaced.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><Button onClick={submit} disabled={pending}>Replace schedule</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></>; }

export function ScheduleAdjustmentForm({ loanId, schedules }: { loanId: string; schedules: Schedule[] }) { const router = useRouter(); const [pending, startTransition] = useTransition(); return <form onSubmit={(event) => { event.preventDefault(); runAction(adjustLoanScheduleAction, new FormData(event.currentTarget), () => { router.push("/admin/loans"); router.refresh(); }, startTransition); }}><SelectField label="Installment" name="scheduleId" options={schedules.map((schedule) => [schedule.id, `#${schedule.installment_number} · ${schedule.due_date}`])} /><div className="mt-5 grid gap-5 sm:grid-cols-2"><SelectField label="Field" name="field" options={["principal", "interest", "penalty", "other"].map((value) => [value, value])} /><Field label="Amount change" name="amountDelta" required /><div className="space-y-2 sm:col-span-2"><Label>Explanation</Label><Textarea name="reason" required minLength={5} /></div></div><AdminFormActions cancelHref="/admin/loans" pending={pending} submitLabel="Apply adjustment" /><input type="hidden" name="loanId" value={loanId} /></form>; }

function Field({ label, name, type, required, value }: { label: string; name: string; type?: string; required?: boolean; value?: string }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={required} inputMode={["principal", "rate", "amount", "amountDelta"].includes(name) ? "decimal" : undefined} defaultValue={value} /></div>; }
function SelectField({ label, name, options }: { label: string; name: string; options: string[][] }) { return <div className="space-y-2"><Label>{label}</Label><Select name={name}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{options.map(([value, text]) => <SelectItem key={value} value={value}>{text}</SelectItem>)}</SelectContent></Select></div>; }
function ControlledSelect({ label, name, value, setValue, options }: { label: string; name: string; value: string; setValue: (value: string) => void; options: string[] }) { return <div className="space-y-2"><Label>{label}</Label><Select name={name} value={value} onValueChange={setValue}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option} value={option}>{option.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div>; }
