import Link from "next/link";
import { CalendarRange, CreditCard, Plus, SlidersHorizontal } from "lucide-react";

import { AdminTableFrame } from "@/components/admin/admin-table-toolbar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export type Loan = { id: string; employee_id: string; loan_type_id: string; account_number: string | null; start_date: string; principal_amount: number; total_payable_amount: number | null; status: string; calculation_source: string; employee_profiles: { employee_number: string; first_name: string; last_name: string } | null; loan_types: { code: string; name: string } | null };
export type Schedule = { id: string; loan_id: string; installment_number: number; due_date: string; principal_due: number; interest_due: number; penalty_due: number; other_due: number; total_due: number; paid_amount: number; status: string };
export type LoanEmployee = { id: string; employee_number: string; first_name: string; last_name: string };
export type LoanTypeOption = { id: string; code: string; name: string; calculation_strategy: string; default_rate: number | null; default_term_count: number | null; installment_frequency: string; rounding_method: string };
export type CreditType = { id: string; name: string };

export function LoanManager({ loans, schedules }: { loans: Loan[]; schedules: Schedule[] }) {
  return <AdminTableFrame><div className="flex items-center justify-between border-b bg-muted/20 p-4"><p className="text-sm font-medium">{loans.length} loans shown</p><Button asChild><Link href="/admin/loans/new"><Plus />Create loan</Link></Button></div>{loans.length ? <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Loan / employee</TableHead><TableHead>Started</TableHead><TableHead className="text-right">Principal</TableHead><TableHead className="text-right">Outstanding</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{loans.map((loan) => { const loanSchedules = schedules.filter((schedule) => schedule.loan_id === loan.id); const outstanding = loanSchedules.reduce((total, schedule) => total + Number(schedule.total_due) - Number(schedule.paid_amount), 0); return <TableRow key={loan.id}><TableCell><p className="font-medium">{loan.loan_types?.code ?? "Loan"} · {loan.employee_profiles?.first_name} {loan.employee_profiles?.last_name}</p><p className="text-sm text-muted-foreground">{loan.account_number ?? "—"}</p></TableCell><TableCell>{loan.start_date}</TableCell><TableCell className="text-right">₱{Number(loan.principal_amount).toLocaleString()}</TableCell><TableCell className="text-right font-medium">₱{outstanding.toLocaleString()}</TableCell><TableCell><Badge variant={loan.status === "active" ? "success" : "secondary"}>{loan.status}</Badge></TableCell><TableCell><div className="flex flex-wrap justify-end gap-2"><Button asChild size="sm" variant="outline"><Link href={`/admin/loans/${loan.id}/payment`}><CreditCard />Payment</Link></Button><Button asChild size="sm" variant="outline"><Link href={`/admin/loans/${loan.id}/schedule`}><CalendarRange />Schedule</Link></Button>{loanSchedules.length ? <Button asChild size="sm" variant="outline"><Link href={`/admin/loans/${loan.id}/adjust`}><SlidersHorizontal />Adjust</Link></Button> : null}</div></TableCell></TableRow>; })}</TableBody></Table></div> : <p className="p-10 text-center text-sm text-muted-foreground">No loans recorded.</p>}</AdminTableFrame>;
}
