"use client";

import { useRouter } from "next/navigation";
import { useTransition } from "react";
import { toast } from "sonner";

import { saveFinancialSettingAction } from "./actions";
import type { SettingRow } from "./settings-manager";
import { AdminFormActions } from "@/components/admin/admin-form-layout";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export function SettingForm({ kind, row, categories }: { kind: string; row?: SettingRow; categories: SettingRow[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  return <form onSubmit={(event) => { event.preventDefault(); startTransition(async () => { const result = await saveFinancialSettingAction(new FormData(event.currentTarget)); if (result.error) { toast.error(result.error); return; } toast.success(result.success); router.push("/admin/settings"); router.refresh(); }); }}><input type="hidden" name="kind" value={kind} /><input type="hidden" name="id" value={row?.id} /><input type="hidden" name="active" value={String(row?.is_active ?? true)} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Code" name="code" required value={row?.code} /><Field label="Name" name="name" required value={row?.name} />{kind === "transaction_types" ? <><SelectField label="Category" name="financialCategoryId" value={row?.financial_category_id} options={categories.map((category) => [category.id, category.name])} /><SelectField label="Direction" name="direction" value={row?.direction ?? "debit"} options={[["debit", "Debit"], ["credit", "Credit"]]} /><SelectField label="Reference numbering" name="referenceStrategy" value={row?.reference_strategy ?? "manual"} options={[["manual", "Manual"], ["sequence", "Automatic sequence"]]} /><Field label="Reference prefix" name="referencePrefix" value={row?.reference_prefix} /></> : null}{!["financial_categories", "transaction_types"].includes(kind) ? <><Field label="Calculation strategy" name="strategy" value={row?.strategy ?? row?.calculation_strategy ?? "manual"} /><Field label="Percentage / rate" name="percentage" value={String(row?.default_rate ?? row?.percentage_rate ?? "")} /><Field label="Fixed amount" name="fixedAmount" value={String(row?.fixed_amount ?? "")} /><Field label="Term length" name="termLength" type="number" value={String(row?.default_term_count ?? "")} /><SelectField label="Installment frequency" name="frequency" value={row?.installment_frequency ?? "monthly"} options={["weekly", "semi_monthly", "monthly", "quarterly"].map((value) => [value, value.replaceAll("_", " ")])} /><SelectField label="Rounding" name="rounding" value={row?.rounding_method ?? "half_up"} options={["half_up", "down", "up"].map((value) => [value, value.replaceAll("_", " ")])} /></> : null}<SelectField label="Balance effect" name="balanceEffect" value={kind === "transaction_types" ? row?.direction === "credit" ? "decrease" : "increase" : row?.balance_effect ?? "neutral"} options={["increase", "decrease", "neutral"].map((value) => [value, value])} /><Field label="Effective from" name="effectiveFrom" type="date" value={row?.effective_from} /><Field label="Effective to" name="effectiveTo" type="date" value={row?.effective_to} /></div><AdminFormActions cancelHref="/admin/settings" pending={pending} submitLabel="Save setting" /></form>;
}
function Field({ label, name, required, value, type }: { label: string; name: string; required?: boolean; value?: string | null; type?: string }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} required={required} defaultValue={value ?? ""} type={type} /></div>; }
function SelectField({ label, name, value, options }: { label: string; name: string; value?: string; options: string[][] }) { return <div className="space-y-2"><Label>{label}</Label><Select name={name} defaultValue={value}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{options.map(([option, text]) => <SelectItem key={option} value={option}>{text}</SelectItem>)}</SelectContent></Select></div>; }
