"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { Pencil, Plus } from "lucide-react";
import { toast } from "sonner";

import { setFinancialSettingStatusAction } from "./actions";
import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export type SettingRow = { id: string; code: string; name: string; is_active: boolean; strategy?: string; calculation_strategy?: string; direction?: string; balance_effect?: string; effective_from?: string | null; effective_to?: string | null; financial_category_id?: string; default_rate?: number | null; percentage_rate?: number | null; fixed_amount?: number | null; default_term_count?: number | null; installment_frequency?: string; rounding_method?: string; reference_strategy?: string; reference_prefix?: string | null };
export const settingLabels: Record<string, string> = { financial_categories: "Financial categories", transaction_types: "Transaction types", interest_methods: "Interest methods", penalty_rules: "Penalty rules", loan_types: "Loan types", rebate_types: "Rebate types" };

export function FinancialSettingsManager({ groups }: { groups: Record<string, SettingRow[]> }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [status, setStatus] = useState<{ kind: string; row: SettingRow }>();
  return <div className="space-y-5">{Object.entries(groups).map(([kind, rows]) => <section key={kind} className="overflow-hidden rounded-lg border"><div className="flex items-center justify-between border-b bg-muted/20 p-4"><h2 className="font-semibold">{settingLabels[kind]}</h2><Button asChild size="sm"><Link href={`/admin/settings/${kind}/new`}><Plus />Add</Link></Button></div>{rows.length ? <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Name</TableHead><TableHead>Method</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.code}</TableCell><TableCell>{row.name}</TableCell><TableCell className="capitalize">{row.direction ?? row.strategy ?? row.calculation_strategy ?? "structured"}</TableCell><TableCell><Badge variant={row.is_active ? "success" : "secondary"}>{row.is_active ? "Active" : "Inactive"}</Badge></TableCell><TableCell><div className="flex justify-end gap-2"><Button asChild size="sm" variant="outline"><Link href={`/admin/settings/${kind}/${row.id}/edit`}><Pencil />Edit</Link></Button><Button size="sm" variant="outline" onClick={() => setStatus({ kind, row })}>{row.is_active ? "Disable" : "Enable"}</Button></div></TableCell></TableRow>)}</TableBody></Table></div> : <p className="p-8 text-center text-sm text-muted-foreground">No settings.</p>}</section>)}<AlertDialog open={Boolean(status)} onOpenChange={(open) => !open && setStatus(undefined)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{status?.row.is_active ? "Disable setting?" : "Enable setting?"}</AlertDialogTitle><AlertDialogDescription>This changes whether the setting can be selected in new records.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><Button disabled={pending} variant={status?.row.is_active ? "destructive" : "default"} onClick={() => { if (!status) return; const data = new FormData(); data.set("kind", status.kind); data.set("id", status.row.id); data.set("active", String(!status.row.is_active)); startTransition(async () => { const result = await setFinancialSettingStatusAction(data); if (result.error) return toast.error(result.error); toast.success(result.success); setStatus(undefined); router.refresh(); }); }}>{status?.row.is_active ? "Disable" : "Enable"}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
