"use client";

import { useMemo, useRef, useState, useTransition } from "react";
import Link from "next/link";
import { File, Folder, Grid2X2, List, RefreshCw, Search, Upload } from "lucide-react";
import * as tus from "tus-js-client";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/client";
import { archiveDocumentAction, finalizeDocumentUploadAction, markDocumentUploadFailedAction, prepareDocumentUploadAction, retryDocumentUploadAction, updateDocumentAction, updateDocumentLimitAction } from "./actions";

type Employee={id:string;employee_number:string;first_name:string;middle_name:string|null;last_name:string};
type Category={id:string;code:string;name:string};
type DocumentRow={id:string;employee_id:string;document_category_id:string;original_filename:string;mime_type:string;size_bytes:number;document_date:string|null;is_employee_visible:boolean;status:string;metadata:unknown;created_at:string;deleted_at:string|null;upload_error:string|null};

export function DocumentArchive({employees,categories,documents,selectedEmployee,selectedCategory,initialView,query,maxMegabytes}:{employees:Employee[];categories:Category[];documents:DocumentRow[];selectedEmployee?:string;selectedCategory?:string;initialView:"grid"|"list";query:string;maxMegabytes:number}){
  const [view,setView]=useState(initialView); const [progress,setProgress]=useState<number|null>(null); const [pending,startTransition]=useTransition(); const fileRef=useRef<HTMLInputElement>(null);
  const employee=employees.find(e=>e.id===selectedEmployee); const category=categories.find(c=>c.id===selectedCategory); const title=category?.name??(employee?`${employee.first_name} ${employee.last_name}`:"Employee documents");
  const filtered=useMemo(()=>documents.filter(d=>(!selectedCategory||d.document_category_id===selectedCategory)&&(!query||`${d.original_filename} ${JSON.stringify(d.metadata)} ${d.document_date??""}`.toLowerCase().includes(query.toLowerCase()))),[documents,selectedCategory,query]);
  const uploadFile=async(file:File,retry?:DocumentRow)=>{if(!selectedEmployee||!selectedCategory)return;let prepared;if(retry)prepared=await retryDocumentUploadAction(retry.id,{name:file.name,type:file.type,size:file.size});else{const fd=new FormData();fd.set("employeeId",selectedEmployee);fd.set("categoryId",selectedCategory);fd.set("filename",file.name);fd.set("mimeType",file.type);fd.set("sizeBytes",String(file.size));fd.set("employeeVisible","true");prepared=await prepareDocumentUploadAction(fd);}if(prepared.error||!prepared.path||!prepared.documentId){toast.error(prepared.error??"Upload could not start.");return;}setProgress(0);try{const supabase=createClient();if(file.size>6_291_456){const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error("Your session expired.");await new Promise<void>((resolve,reject)=>{const task=new tus.Upload(file,{endpoint:`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/upload/resumable`,headers:{authorization:`Bearer ${session.access_token}`},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:"employee-documents",objectName:prepared.path!,contentType:file.type,cacheControl:"3600"},onError:reject,onProgress:(sent,total)=>setProgress(Math.round(sent/total*100)),onSuccess:()=>resolve()});task.start();});}else{const{error}=await supabase.storage.from("employee-documents").upload(prepared.path,file,{contentType:file.type,upsert:false});if(error)throw error;setProgress(100);}const finished=await finalizeDocumentUploadAction(prepared.documentId);if(finished.error)throw new Error(finished.error);toast.success(finished.success);window.location.reload();}catch(error){const message=error instanceof Error?error.message:"Upload failed.";await markDocumentUploadFailedAction(prepared.documentId,message);toast.error(`${message} Use Retry on the pending file.`);}finally{setProgress(null);}};
  return <div className="space-y-6"><div className="flex flex-col gap-4 border-b pb-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wide text-primary">Private archive</p><h1 className="text-3xl font-bold">{title}</h1><p className="mt-2 text-muted-foreground">Private files are organized by employee, then category. Signed links expire after five minutes.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setView(view==="grid"?"list":"grid")}>{view==="grid"?<List/>:<Grid2X2/>}{view==="grid"?"List view":"Grid view"}</Button>{category&&<><input ref={fileRef} className="hidden" type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{const f=e.target.files?.[0];if(f)void uploadFile(f)}}/><Button disabled={progress!==null} onClick={()=>fileRef.current?.click()}><Upload/>Upload file</Button></>}</div></div>
  <form className="flex gap-2"><input type="hidden" name="employee" value={selectedEmployee??""}/><input type="hidden" name="category" value={selectedCategory??""}/><Input name="q" defaultValue={query} placeholder="Search employee, filename, date, or metadata"/><Button variant="outline"><Search/>Search</Button></form>
  {progress!==null&&<div className="rounded-lg border p-4" role="status"><div className="mb-2 flex justify-between"><span>Uploading and verifying…</span><span>{progress}%</span></div><div className="h-2 rounded bg-muted"><div className="h-2 rounded bg-primary" style={{width:`${progress}%`}}/></div></div>}
  {selectedEmployee&&<div className="text-sm"><Link className="text-primary hover:underline" href="/admin/documents">Employees</Link>{category&&<> / <Link className="text-primary hover:underline" href={`/admin/documents?employee=${selectedEmployee}`}>Categories</Link></>}</div>}
  {!employee?<><form action={async fd=>{startTransition(async()=>{const r=await updateDocumentLimitAction(fd);if(r.error)toast.error(r.error);else toast.success(r.success)})}} className="flex max-w-lg items-end gap-2 rounded-xl border bg-card p-4"><label className="flex-1 text-sm font-medium">Maximum file size (MB)<Input name="megabytes" type="number" min={1} max={50} defaultValue={maxMegabytes}/></label><Button variant="outline" disabled={pending}>Save limit</Button></form><FolderGrid items={employees.filter(e=>!query||`${e.employee_number} ${e.first_name} ${e.middle_name??""} ${e.last_name}`.toLowerCase().includes(query.toLowerCase())).map(e=>({id:e.id,label:`${e.last_name}, ${e.first_name}`,sub:e.employee_number,href:`/admin/documents?employee=${e.id}`}))}/></>:!category?<FolderGrid items={categories.filter(c=>!query||`${c.code} ${c.name}`.toLowerCase().includes(query.toLowerCase())).map(c=>({id:c.id,label:c.name,sub:`${documents.filter(d=>d.document_category_id===c.id&&d.deleted_at===null).length} files`,href:`/admin/documents?employee=${employee.id}&category=${c.id}`}))}/>:filtered.length===0?<Empty/>:<div className={view==="grid"?"grid gap-4 md:grid-cols-2 xl:grid-cols-3":"divide-y rounded-lg border"}>{filtered.map(d=><DocumentItem key={d.id} document={d} categories={categories} list={view==="list"} pending={pending} run={startTransition} retry={file=>void uploadFile(file,d)}/>)}</div>}
  </div>;
}

function FolderGrid({items}:{items:{id:string;label:string;sub:string;href:string}[]}){return items.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map(i=><Link key={i.id} href={i.href} className="flex min-h-24 items-center gap-4 rounded-xl border bg-card p-5 hover:border-primary focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring"><Folder className="size-8 text-primary"/><span><strong className="block">{i.label}</strong><small className="text-muted-foreground">{i.sub}</small></span></Link>)}</div>:<Empty/>}
function Empty(){return <div className="rounded-xl border border-dashed p-12 text-center"><Folder className="mx-auto mb-3 size-10 text-muted-foreground"/><h2 className="font-semibold">Nothing here yet</h2><p className="text-sm text-muted-foreground">Choose another folder or upload the first authorized file.</p></div>}
function DocumentItem({document,categories,list,pending,run,retry}:{document:DocumentRow;categories:Category[];list:boolean;pending:boolean;run:(cb:()=>void)=>void;retry:(file:File)=>void}){const archived=!!document.deleted_at;const retryRef=useRef<HTMLInputElement>(null);return <article className={`space-y-3 bg-card p-4 ${list?"":"rounded-xl border"}`}><div className="flex gap-3"><File className="mt-1 size-6 text-primary"/><div className="min-w-0"><h3 className="truncate font-semibold">{document.original_filename}</h3><p className="text-sm text-muted-foreground">{Math.ceil(document.size_bytes/1024)} KB · {document.document_date??new Date(document.created_at).toLocaleDateString()}</p>{document.upload_error&&<p className="text-sm text-destructive">{document.upload_error}</p>}</div></div>{!archived&&document.status==="available"&&<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" asChild><a href={`/api/documents/${document.id}`} target="_blank">Preview</a></Button><Button size="sm" variant="outline" asChild><a href={`/api/documents/${document.id}?download=1`}>Download</a></Button></div>}{!archived&&document.status==="pending"&&<><input ref={retryRef} className="hidden" type="file" accept={document.mime_type} onChange={e=>{const file=e.target.files?.[0];if(file)retry(file)}}/><Button size="sm" variant="outline" onClick={()=>retryRef.current?.click()}><RefreshCw/>Retry same file</Button></>}<form action={async fd=>{run(async()=>{const r=await updateDocumentAction(fd);if(r.error)toast.error(r.error);else toast.success(r.success)})}} className="grid gap-2"><input type="hidden" name="documentId" value={document.id}/><Input name="filename" defaultValue={document.original_filename} aria-label="Filename"/><select name="categoryId" defaultValue={document.document_category_id} className="h-10 rounded-lg border bg-background px-3">{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><Input name="reason" placeholder="Reason for rename or move"/><Button size="sm" variant="outline" disabled={pending}>Save metadata</Button></form><form action={async fd=>{run(async()=>{const r=await archiveDocumentAction(fd);if(r.error)toast.error(r.error);else toast.success(r.success)})}} className="flex gap-2"><input type="hidden" name="documentId" value={document.id}/><input type="hidden" name="operation" value={archived?"restore":"soft_delete"}/><Input name="reason" required minLength={5} placeholder={archived?"Restore reason":"Archive reason"}/><Button size="sm" variant={archived?"outline":"destructive"} disabled={pending}>{archived?<><RefreshCw/>Restore</>:"Archive"}</Button></form></article>}
